version: '3'

services:
  flask-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    volumes:
      - ./python-backend:/app
    working_dir: /app
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/windForecaster
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://flask-backend:5000
    ports:
      - "3000:80"
    depends_on:
      - flask-backend

  mongo:
    build:
      context: ./mongo-init
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo-data:
