version: '3'

networks:
  wind-forecaster-network:
    driver: bridge

services:
  flask-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    volumes:
      - ./python-backend:/app
    working_dir: /app
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
          - FLASK_APP=main.py
          - FLASK_DEBUG=True
          - FLASK_HOST=0.0.0.0
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=pass
          - MONGODB_URI=mongodb://wind-forecaster-mongo:27017/windForecaster
    ports:
      - "5000:5000"
    networks:
      - wind-forecaster-network
    depends_on:
      - wind-forecaster-mongo


  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    volumes:
    - ./react-frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://flask-backend:5000
      - HOST=0.0.0.0
    ports:
      - "3000:80"
      - "9229:9229" # for debugging
    networks:
      - wind-forecaster-network
    depends_on:
      - flask-backend

  wind-forecaster-mongo:
    build:
      context: ./mongo-init
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    networks:
      - wind-forecaster-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo-data:
